# Generated by Django 4.2 on 2023-04-24 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_cargo_jacket_jeans_oversize'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hoodie',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='hoodie',
            name='category',
            field=models.CharField(blank=True, choices=[('Hoodie', 'Hoodie'), ('Cargo', 'Cargo'), ('Jeans', 'Jeans'), ('Oversize', 'Oversize'), ('Jacket', 'Jacket')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='hoodie',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='jacket',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='jeans',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='oversize',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
