# Generated by Django 4.2 on 2023-04-24 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_hoodie_options_hoodie_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jeans',
            new_name='Jean',
        ),
    ]
