# Generated by Django 4.2 on 2023-05-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('price', models.DecimalField(decimal_places=1, max_digits=5)),
                ('image', models.ImageField(upload_to='images/%y/%m')),
                ('active', models.BooleanField(default=True)),
                ('category', models.CharField(blank=True, choices=[('Hoodie', 'Hoodie'), ('Cargo', 'Cargo'), ('Jeans', 'Jeans'), ('Oversize', 'Oversize'), ('Jacket', 'Jacket')], max_length=100, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
