# Generated by Django 4.2 on 2023-05-18 00:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='Cart',
        ),
        migrations.RemoveField(
            model_name='hoodie',
            name='category',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
