# Generated by Django 4.2 on 2023-05-18 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_cartitem_cart_remove_hoodie_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='Cargo',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='Hoodie',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='Jacket',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='Jean',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='Oversize',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='Cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cartitems', to='products.cart'),
            preserve_default=False,
        ),
    ]
