# Generated by Django 4.2 on 2023-05-18 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_cartitem_cargo_remove_cartitem_hoodie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='Cart',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.cart'),
        ),
    ]
