# Generated by Django 4.2 on 2023-05-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_rename_cart_cartitem_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Hoodie',
        ),
        migrations.DeleteModel(
            name='Jacket',
        ),
        migrations.DeleteModel(
            name='Jean',
        ),
        migrations.DeleteModel(
            name='Oversize',
        ),
        migrations.DeleteModel(
            name='RegUser',
        ),
    ]
